"""atualizando tabelas produto e fornecedor

Revision ID: 55de9448f8ec
Revises: efc27b830671
Create Date: 2024-01-31 14:45:04.011428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55de9448f8ec'
down_revision: Union[str, None] = 'efc27b830671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('fornecedor_id', sa.Integer(), nullable=False))
    op.alter_column('produto', 'preco_unico',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8, decimal_return_scale=2),
               existing_nullable=False)
    op.alter_column('produto', 'receita',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8, decimal_return_scale=2),
               existing_nullable=False)
    op.drop_constraint('produto_fornecedor_fkey', 'produto', type_='foreignkey')
    op.create_foreign_key(None, 'produto', 'fornecedor', ['fornecedor_id'], ['id'])
    op.drop_column('produto', 'fornecedor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('fornecedor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.create_foreign_key('produto_fornecedor_fkey', 'produto', 'fornecedor', ['fornecedor'], ['id'])
    op.alter_column('produto', 'receita',
               existing_type=sa.Float(precision=8, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('produto', 'preco_unico',
               existing_type=sa.Float(precision=8, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('produto', 'fornecedor_id')
    # ### end Alembic commands ###
