"""atualizando campo da tabela produto

Revision ID: 5de5aa96196e
Revises: 55de9448f8ec
Create Date: 2024-01-31 14:56:32.345549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de5aa96196e'
down_revision: Union[str, None] = '55de9448f8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('fornecido_por', sa.Integer(), nullable=False))
    op.alter_column('produto', 'preco_unico',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8, decimal_return_scale=2),
               existing_nullable=False)
    op.alter_column('produto', 'receita',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8, decimal_return_scale=2),
               existing_nullable=False)
    op.drop_constraint('produto_fornecedor_id_fkey', 'produto', type_='foreignkey')
    op.create_foreign_key(None, 'produto', 'fornecedor', ['fornecido_por'], ['id'])
    op.drop_column('produto', 'fornecedor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.create_foreign_key('produto_fornecedor_id_fkey', 'produto', 'fornecedor', ['fornecedor_id'], ['id'])
    op.alter_column('produto', 'receita',
               existing_type=sa.Float(precision=8, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('produto', 'preco_unico',
               existing_type=sa.Float(precision=8, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('produto', 'fornecido_por')
    # ### end Alembic commands ###
