"""criando tabelas produto e fornecedor

Revision ID: efc27b830671
Revises: 
Create Date: 2024-01-31 08:14:54.432536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc27b830671'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('empresa', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('quantidade_vendida', sa.Integer(), nullable=False),
    sa.Column('preco_unico', sa.Float(precision=8, decimal_return_scale=2), nullable=False),
    sa.Column('receita', sa.Float(precision=8, decimal_return_scale=2), nullable=False),
    sa.Column('fornecedor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
